name: Build the HelloOpenGL project

on:
  workflow_dispatch:
    inputs:
      target_os:
        description: "Select the OS to compile for"
        required: true
        type: choice
        options:
          - ubuntu
          - windows
          - macos
        default: ubuntu

jobs:
  build:
    runs-on: ${{ github.event.inputs.target_os }}-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Graalvm
        uses: graalvm/setup-graalvm@v1
        with:
          version: "latest"
          java-version: "21"
          components: "native-image"
        run: ./gradlew nativeCompile

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: native-app-${{ github.event.inputs.target_os }}
          path: |
            target/*
            build/native/nativeCompile/*
